### ISSUE TITLE
exec: Unable to find a path to the node binary. Please manually set config.execPath

### ISSUE THREAD

**Issue by devYoungyang** [nfischer/shelljs-exec-proxy#19] opened 2019-10-16 02:08 UTC
报这个exec: Unable to find a path to the node binary. Please manually set config.execPath 错误是什么原因？

**Comment by nfischer** [comment] 2019-10-18 05:30
Duplicate of shelljs/shelljs#972

**Closed by nfischer** 2019-10-18 05:30 UTC
